global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'tp-backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 10s
    metrics_path: '/api/actuator/prometheus'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
