server:
  port: 8080

spring:
  application:
    name: labpay-backend
  
  datasource:
    url: jdbc:h2:mem:labpay
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  security:
    user:
      name: admin
      password: admin

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours

logging:
  level:
    com.labpay: DEBUG
    org.springframework.security: DEBUG